//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AmanCompany.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Product
    {
        public int Id { get; set; }
        [Required, StringLength(100), Display(Name = "Name")]
        public string Name { get; set; }
        [Required, StringLength(500), Display(Name = "Name")]
        public string Image { get; set; }
        [Required, StringLength(100), Display(Name = "Product Type")]
        public string Product_Type { get; set; }
        [Required, StringLength(100), Display(Name = "Delivary Date")]
        public Nullable<System.DateTime> DelivaryDate { get; set; }
        [Required, StringLength(100), Display(Name = "Product Wright")]
        public Nullable<double> ProductWeight { get; set; }
        public Nullable<double> price { get; set; }
        public Nullable<int> Quantity { get; set; }
    }
}
